"""empty message

Revision ID: 15bbe69411cc
Revises: aaefac4fa136
Create Date: 2019-12-07 14:21:55.587195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bbe69411cc'
down_revision = 'aaefac4fa136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
